### ISSUE TITLE
Test geoms with maps and projections and add examples

### ISSUE THREAD

**Issue by aphalo** [aphalo/ggpp#1]
Brief description of the problem

Support for sf data for maps has been added to 'ggplot2' some time ago, but 'ggpp' has not been tested for labelling of maps. 

Example user interface and/or plot output.

Add examples to documentation, and unit tests to testthat folder.

**Comment by aphalo** [comment]
Statistic `stat_sf_coordinates()` can be used to translate map coordinates into _x_ and _y_  coordinates. This needs testing and examples need to be added to the vignettes. Even if this solves the problem in many cases it leaves unresolved the problem for those cases where the elements being plotted are computed by a different statistic as statistics cannot be concatenated...

**Comment by aphalo** [comment]
Rather than in the vignette these examples can be given in a post at the website.

**Comment by r2evans** [comment]
I'm actually really interested in how to use `ggpp::position_nudge_line()` with plots that include `ggrepel::geom_repel_text(..., stat = "sf_coordinates")`. Any chance you have a draft of your post that I can use?

**Comment by aphalo** [comment]
I am sorry, but I do not yet have even a draft. I closed the issue as I have a separate repo for the web site. I do not even know if `ggplot2::position_nudge()` works in such a case. Some days ago I quickly tried some of the geoms and they seemed to work o.k. If `ggplot2::position_nudge()` works, it is likely that `ggpp::position_nudge_line()` will work as it uses the same input and output variables. I am not sure how the projection used in the map will affect the shape of the line. If you can draw the map without using `stat = "sf_coordinates"` it is quite posible that the _position_ functions work as well.

If you have time, I suggest that you try editing some of the 'ggplot2' examples, and report back here what you find. If it does not work, I could use your example to try to make 'ggpp' work with maps. If it works, I could use your code for further tests, or in the blog post, acknowledging your contribution. If possible, use 'ggplot2' 3.5.1 and 'ggpp' 0.5.7 that was accepted this afternoon by CRAN.

**Comment by aphalo** [comment]
The website issue is at: https://github.com/aphalo/r4p-blog/issues/2
