### ISSUE TITLE
Tag CRAN release versions?

### ISSUE THREAD

**Issue by mschubert** [aphalo/ggpp#20]
It would be great if the CRAN release versions were also tagged (and maybe mirrored by a github "release") in this repository, so a user can compare which code changed between versions.

The code for this would be simply:

```sh
git tag -a "vX.Y" # with release notes
git tag "vX.Y" # without
```

on the same commit as is pushed to CRAN.

For an example, [see here](https://github.com/mschubert/narray/releases) (annotated tags and releases) or [in `ggrepel`](https://github.com/slowkow/ggrepel/tags) (tags only).

**Comment by aphalo** [comment]
Thanks! You are right. Until now I have used ordinary tags. Do you know if I can retrospectively create releases?

**Comment by aphalo** [comment]
I had not pushed the tags, my bad. When I tried today to push them I encountered a problem. I will try to fix this in the evening.

**Comment by aphalo** [comment]
The tags are now in GitHub.
