### ISSUE TITLE
Minor bug in stat_dens1d_filter example

### ISSUE THREAD

**Issue by joshuaulrich** [aphalo/ggpp#53]
[This line](https://github.com/aphalo/ggpp/blob/6260c0e76549ce6dfc9e473e2434a6601b70d193/R/stat-dens1d-filter.r#L212) is supposed to check whether 'gginnards' is installed, but checks for 'ggrepel' instead. That causes the example to fail if 'gginnards' is not installed.

**Comment by aphalo** [comment]
@joshuaulrich Many thanks for reporting this bug! Fixed now, in  stat-dens1d-filter.r and in stat-dens2d-filter.r
If you want to install the fixed version from a CRAN-like repo, it will be available in some hours at: https://aphalo.r-universe.dev/ggpp as version 0.5.7.9000
